<?php
/**
 * PreconfiguredproductsApi
 * PHP version 5
 *
 * @category Class
 * @package  gooten.api.client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

namespace gooten.api;

use \gooten.api.client\Configuration;
use \gooten.api.client\ApiClient;
use \gooten.api.client\ApiException;
use \gooten.api.client\ObjectSerializer;

/**
 * PreconfiguredproductsApi Class Doc Comment
 *
 * @category Class
 * @package  gooten.api.client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PreconfiguredproductsApi
{

    /**
     * API Client
     * @var \gooten.api.client\ApiClient instance of the ApiClient
     */
    protected $apiClient;
  
    /**
     * Constructor
     * @param \gooten.api.client\ApiClient|null $apiClient The api client to use
     */
    function __construct($apiClient = null)
    {
        if ($apiClient == null) {
            $apiClient = new ApiClient();
            $apiClient->getConfig()->setHost('https://localhost/api');
        }
  
        $this->apiClient = $apiClient;
    }
  
    /**
     * Get API client
     * @return \gooten.api.client\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }
  
    /**
     * Set the API client
     * @param \gooten.api.client\ApiClient $apiClient set the API client
     * @return PreconfiguredproductsApi
     */
    public function setApiClient(ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }
  
    
    /**
     * createPreconfiguredproducts
     *
     * Insert a preconfigured product
     *
     * @param \gooten.api.model\PreconfiguredProductInsert $preconfigured_product_insert The product to be inserted (required)
     * @param int $version Version of the api being used (required)
     * @param string $source Description of the source-- ios, android, api (required)
     * @return \gooten.api.model\PreconfiguredProductsInsertResponse
     * @throws \gooten.api.client\ApiException on non-2xx response
     */
    public function createPreconfiguredproducts($preconfigured_product_insert, $version, $source)
    {
        list($response, $statusCode, $httpHeader) = $this->createPreconfiguredproductsWithHttpInfo ($preconfigured_product_insert, $version, $source);
        return $response; 
    }


    /**
     * createPreconfiguredproductsWithHttpInfo
     *
     * Insert a preconfigured product
     *
     * @param \gooten.api.model\PreconfiguredProductInsert $preconfigured_product_insert The product to be inserted (required)
     * @param int $version Version of the api being used (required)
     * @param string $source Description of the source-- ios, android, api (required)
     * @return Array of \gooten.api.model\PreconfiguredProductsInsertResponse, HTTP status code, HTTP response headers (array of strings)
     * @throws \gooten.api.client\ApiException on non-2xx response
     */
    public function createPreconfiguredproductsWithHttpInfo($preconfigured_product_insert, $version, $source)
    {
        
        // verify the required parameter 'preconfigured_product_insert' is set
        if ($preconfigured_product_insert === null) {
            throw new \InvalidArgumentException('Missing the required parameter $preconfigured_product_insert when calling createPreconfiguredproducts');
        }
        // verify the required parameter 'version' is set
        if ($version === null) {
            throw new \InvalidArgumentException('Missing the required parameter $version when calling createPreconfiguredproducts');
        }
        // verify the required parameter 'source' is set
        if ($source === null) {
            throw new \InvalidArgumentException('Missing the required parameter $source when calling createPreconfiguredproducts');
        }
  
        // parse inputs
        $resourcePath = "/v/{version}/source/{source}/preconfiguredproducts/";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        // path params
        
        if ($version !== null) {
            $resourcePath = str_replace(
                "{" . "version" . "}",
                $this->apiClient->getSerializer()->toPathValue($version),
                $resourcePath
            );
        }// path params
        
        if ($source !== null) {
            $resourcePath = str_replace(
                "{" . "source" . "}",
                $this->apiClient->getSerializer()->toPathValue($source),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($preconfigured_product_insert)) {
            $_tempBody = $preconfigured_product_insert;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'POST',
                $queryParams, $httpBody,
                $headerParams, '\gooten.api.model\PreconfiguredProductsInsertResponse'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\gooten.api.client\ObjectSerializer::deserialize($response, '\gooten.api.model\PreconfiguredProductsInsertResponse', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \gooten.api.client\ObjectSerializer::deserialize($e->getResponseBody(), '\gooten.api.model\PreconfiguredProductsInsertResponse', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * deletePreconfiguredproducts
     *
     * Delete a preconfigured product
     *
     * @param int $version Version of the api being used (required)
     * @param string $source Description of the source-- ios, android, api (required)
     * @param string $sku The preconfigured product&#39;s sku. (optional)
     * @return \gooten.api.model\PreconfiguredProductsInsertResponse
     * @throws \gooten.api.client\ApiException on non-2xx response
     */
    public function deletePreconfiguredproducts($version, $source, $sku = null)
    {
        list($response, $statusCode, $httpHeader) = $this->deletePreconfiguredproductsWithHttpInfo ($version, $source, $sku);
        return $response; 
    }


    /**
     * deletePreconfiguredproductsWithHttpInfo
     *
     * Delete a preconfigured product
     *
     * @param int $version Version of the api being used (required)
     * @param string $source Description of the source-- ios, android, api (required)
     * @param string $sku The preconfigured product&#39;s sku. (optional)
     * @return Array of \gooten.api.model\PreconfiguredProductsInsertResponse, HTTP status code, HTTP response headers (array of strings)
     * @throws \gooten.api.client\ApiException on non-2xx response
     */
    public function deletePreconfiguredproductsWithHttpInfo($version, $source, $sku = null)
    {
        
        // verify the required parameter 'version' is set
        if ($version === null) {
            throw new \InvalidArgumentException('Missing the required parameter $version when calling deletePreconfiguredproducts');
        }
        // verify the required parameter 'source' is set
        if ($source === null) {
            throw new \InvalidArgumentException('Missing the required parameter $source when calling deletePreconfiguredproducts');
        }
  
        // parse inputs
        $resourcePath = "/v/{version}/source/{source}/preconfiguredproducts/";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        // query params
        
        if ($sku !== null) {
            $queryParams['sku'] = $this->apiClient->getSerializer()->toQueryValue($sku);
        }
        
        // path params
        
        if ($version !== null) {
            $resourcePath = str_replace(
                "{" . "version" . "}",
                $this->apiClient->getSerializer()->toPathValue($version),
                $resourcePath
            );
        }// path params
        
        if ($source !== null) {
            $resourcePath = str_replace(
                "{" . "source" . "}",
                $this->apiClient->getSerializer()->toPathValue($source),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'DELETE',
                $queryParams, $httpBody,
                $headerParams, '\gooten.api.model\PreconfiguredProductsInsertResponse'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\gooten.api.client\ObjectSerializer::deserialize($response, '\gooten.api.model\PreconfiguredProductsInsertResponse', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \gooten.api.client\ObjectSerializer::deserialize($e->getResponseBody(), '\gooten.api.model\PreconfiguredProductsInsertResponse', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * getPreconfiguredproducts
     *
     * Get a list of your preconfigured products
     *
     * @param string $country_code The country code where it would be shipped to. For example, &#39;US&#39; or &#39;CA&#39; (required)
     * @param int $version Version of the api being used (required)
     * @param string $source Description of the source-- ios, android, api (required)
     * @param string $language_code Two-character language code, defaults to \&quot;en\&quot; (english) (optional)
     * @param string $currency_code Three character currency code, defaults to \&quot;USD\&quot; (united states dollar) (optional)
     * @return \gooten.api.model\PreconfiguredProductsResponse
     * @throws \gooten.api.client\ApiException on non-2xx response
     */
    public function getPreconfiguredproducts($country_code, $version, $source, $language_code = null, $currency_code = null)
    {
        list($response, $statusCode, $httpHeader) = $this->getPreconfiguredproductsWithHttpInfo ($country_code, $version, $source, $language_code, $currency_code);
        return $response; 
    }


    /**
     * getPreconfiguredproductsWithHttpInfo
     *
     * Get a list of your preconfigured products
     *
     * @param string $country_code The country code where it would be shipped to. For example, &#39;US&#39; or &#39;CA&#39; (required)
     * @param int $version Version of the api being used (required)
     * @param string $source Description of the source-- ios, android, api (required)
     * @param string $language_code Two-character language code, defaults to \&quot;en\&quot; (english) (optional)
     * @param string $currency_code Three character currency code, defaults to \&quot;USD\&quot; (united states dollar) (optional)
     * @return Array of \gooten.api.model\PreconfiguredProductsResponse, HTTP status code, HTTP response headers (array of strings)
     * @throws \gooten.api.client\ApiException on non-2xx response
     */
    public function getPreconfiguredproductsWithHttpInfo($country_code, $version, $source, $language_code = null, $currency_code = null)
    {
        
        // verify the required parameter 'country_code' is set
        if ($country_code === null) {
            throw new \InvalidArgumentException('Missing the required parameter $country_code when calling getPreconfiguredproducts');
        }
        // verify the required parameter 'version' is set
        if ($version === null) {
            throw new \InvalidArgumentException('Missing the required parameter $version when calling getPreconfiguredproducts');
        }
        // verify the required parameter 'source' is set
        if ($source === null) {
            throw new \InvalidArgumentException('Missing the required parameter $source when calling getPreconfiguredproducts');
        }
  
        // parse inputs
        $resourcePath = "/v/{version}/source/{source}/preconfiguredproducts/";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        // query params
        
        if ($country_code !== null) {
            $queryParams['countryCode'] = $this->apiClient->getSerializer()->toQueryValue($country_code);
        }// query params
        
        if ($language_code !== null) {
            $queryParams['languageCode'] = $this->apiClient->getSerializer()->toQueryValue($language_code);
        }// query params
        
        if ($currency_code !== null) {
            $queryParams['currencyCode'] = $this->apiClient->getSerializer()->toQueryValue($currency_code);
        }
        
        // path params
        
        if ($version !== null) {
            $resourcePath = str_replace(
                "{" . "version" . "}",
                $this->apiClient->getSerializer()->toPathValue($version),
                $resourcePath
            );
        }// path params
        
        if ($source !== null) {
            $resourcePath = str_replace(
                "{" . "source" . "}",
                $this->apiClient->getSerializer()->toPathValue($source),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'GET',
                $queryParams, $httpBody,
                $headerParams, '\gooten.api.model\PreconfiguredProductsResponse'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\gooten.api.client\ObjectSerializer::deserialize($response, '\gooten.api.model\PreconfiguredProductsResponse', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \gooten.api.client\ObjectSerializer::deserialize($e->getResponseBody(), '\gooten.api.model\PreconfiguredProductsResponse', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * updatePreconfiguredproducts
     *
     * Update a preconfigured product
     *
     * @param \gooten.api.model\PreconfiguredProductInsert $preconfigured_product_insert The product to be inserted (required)
     * @param int $version Version of the api being used (required)
     * @param string $source Description of the source-- ios, android, api (required)
     * @return \gooten.api.model\PreconfiguredProductsInsertResponse
     * @throws \gooten.api.client\ApiException on non-2xx response
     */
    public function updatePreconfiguredproducts($preconfigured_product_insert, $version, $source)
    {
        list($response, $statusCode, $httpHeader) = $this->updatePreconfiguredproductsWithHttpInfo ($preconfigured_product_insert, $version, $source);
        return $response; 
    }


    /**
     * updatePreconfiguredproductsWithHttpInfo
     *
     * Update a preconfigured product
     *
     * @param \gooten.api.model\PreconfiguredProductInsert $preconfigured_product_insert The product to be inserted (required)
     * @param int $version Version of the api being used (required)
     * @param string $source Description of the source-- ios, android, api (required)
     * @return Array of \gooten.api.model\PreconfiguredProductsInsertResponse, HTTP status code, HTTP response headers (array of strings)
     * @throws \gooten.api.client\ApiException on non-2xx response
     */
    public function updatePreconfiguredproductsWithHttpInfo($preconfigured_product_insert, $version, $source)
    {
        
        // verify the required parameter 'preconfigured_product_insert' is set
        if ($preconfigured_product_insert === null) {
            throw new \InvalidArgumentException('Missing the required parameter $preconfigured_product_insert when calling updatePreconfiguredproducts');
        }
        // verify the required parameter 'version' is set
        if ($version === null) {
            throw new \InvalidArgumentException('Missing the required parameter $version when calling updatePreconfiguredproducts');
        }
        // verify the required parameter 'source' is set
        if ($source === null) {
            throw new \InvalidArgumentException('Missing the required parameter $source when calling updatePreconfiguredproducts');
        }
  
        // parse inputs
        $resourcePath = "/v/{version}/source/{source}/preconfiguredproducts/";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        // path params
        
        if ($version !== null) {
            $resourcePath = str_replace(
                "{" . "version" . "}",
                $this->apiClient->getSerializer()->toPathValue($version),
                $resourcePath
            );
        }// path params
        
        if ($source !== null) {
            $resourcePath = str_replace(
                "{" . "source" . "}",
                $this->apiClient->getSerializer()->toPathValue($source),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($preconfigured_product_insert)) {
            $_tempBody = $preconfigured_product_insert;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'PUT',
                $queryParams, $httpBody,
                $headerParams, '\gooten.api.model\PreconfiguredProductsInsertResponse'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\gooten.api.client\ObjectSerializer::deserialize($response, '\gooten.api.model\PreconfiguredProductsInsertResponse', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \gooten.api.client\ObjectSerializer::deserialize($e->getResponseBody(), '\gooten.api.model\PreconfiguredProductsInsertResponse', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
}
