<?php


/**
 * Order
 *
 * PHP version 5
 *
 * @category Class
 * @package  gooten.api.client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace gooten.api.model;

use \ArrayAccess;
/**
 * Order Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     gooten.api.client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Order implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'ship_to_address' => '\gooten.api.model\ShipToAddress',
        'items' => '\gooten.api.model\OrderItem[]',
        'payment' => '\gooten.api.model\Payment',
        'coupon_code' => 'string'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'ship_to_address' => 'ShipToAddress',
        'items' => 'Items',
        'payment' => 'Payment',
        'coupon_code' => 'CouponCode'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'ship_to_address' => 'setShipToAddress',
        'items' => 'setItems',
        'payment' => 'setPayment',
        'coupon_code' => 'setCouponCode'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'ship_to_address' => 'getShipToAddress',
        'items' => 'getItems',
        'payment' => 'getPayment',
        'coupon_code' => 'getCouponCode'
    );
  
    
    /**
      * $ship_to_address 
      * @var \gooten.api.model\ShipToAddress
      */
    protected $ship_to_address;
    
    /**
      * $items 
      * @var \gooten.api.model\OrderItem[]
      */
    protected $items;
    
    /**
      * $payment 
      * @var \gooten.api.model\Payment
      */
    protected $payment;
    
    /**
      * $coupon_code 
      * @var string
      */
    protected $coupon_code;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->ship_to_address = $data["ship_to_address"];
            $this->items = $data["items"];
            $this->payment = $data["payment"];
            $this->coupon_code = $data["coupon_code"];
        }
    }
    
    /**
     * Gets ship_to_address
     * @return \gooten.api.model\ShipToAddress
     */
    public function getShipToAddress()
    {
        return $this->ship_to_address;
    }
  
    /**
     * Sets ship_to_address
     * @param \gooten.api.model\ShipToAddress $ship_to_address 
     * @return $this
     */
    public function setShipToAddress($ship_to_address)
    {
        
        $this->ship_to_address = $ship_to_address;
        return $this;
    }
    
    /**
     * Gets items
     * @return \gooten.api.model\OrderItem[]
     */
    public function getItems()
    {
        return $this->items;
    }
  
    /**
     * Sets items
     * @param \gooten.api.model\OrderItem[] $items 
     * @return $this
     */
    public function setItems($items)
    {
        
        $this->items = $items;
        return $this;
    }
    
    /**
     * Gets payment
     * @return \gooten.api.model\Payment
     */
    public function getPayment()
    {
        return $this->payment;
    }
  
    /**
     * Sets payment
     * @param \gooten.api.model\Payment $payment 
     * @return $this
     */
    public function setPayment($payment)
    {
        
        $this->payment = $payment;
        return $this;
    }
    
    /**
     * Gets coupon_code
     * @return string
     */
    public function getCouponCode()
    {
        return $this->coupon_code;
    }
  
    /**
     * Sets coupon_code
     * @param string $coupon_code 
     * @return $this
     */
    public function setCouponCode($coupon_code)
    {
        
        $this->coupon_code = $coupon_code;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\gooten.api.client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\gooten.api.client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}


