<?php
/**
 * PostOrder
 *
 * PHP version 5
 *
 * @category Class
 * @package  gooten.api.client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace gooten.api.model;

use \ArrayAccess;
/**
 * PostOrder Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     gooten.api.client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PostOrder implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'ship_to_address' => '\gooten.api.model\ShipToAddress',
        'billing_address' => '\gooten.api.model\ShipToAddress',
        'items' => '\gooten.api.model\PostOrderItem[]',
        'payment' => '\gooten.api.model\OrderPayment',
        'source_id' => 'string',
        'is_pre_submit' => 'bool',
        'coupon_code' => 'string',
        'meta' => '\gooten.api.model\Meta'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'ship_to_address' => 'ShipToAddress',
        'billing_address' => 'BillingAddress',
        'items' => 'Items',
        'payment' => 'Payment',
        'source_id' => 'SourceId',
        'is_pre_submit' => 'IsPreSubmit',
        'coupon_code' => 'CouponCode',
        'meta' => 'Meta'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'ship_to_address' => 'setShipToAddress',
        'billing_address' => 'setBillingAddress',
        'items' => 'setItems',
        'payment' => 'setPayment',
        'source_id' => 'setSourceId',
        'is_pre_submit' => 'setIsPreSubmit',
        'coupon_code' => 'setCouponCode',
        'meta' => 'setMeta'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'ship_to_address' => 'getShipToAddress',
        'billing_address' => 'getBillingAddress',
        'items' => 'getItems',
        'payment' => 'getPayment',
        'source_id' => 'getSourceId',
        'is_pre_submit' => 'getIsPreSubmit',
        'coupon_code' => 'getCouponCode',
        'meta' => 'getMeta'
    );
  
    
    /**
      * $ship_to_address 
      * @var \gooten.api.model\ShipToAddress
      */
    protected $ship_to_address;
    
    /**
      * $billing_address 
      * @var \gooten.api.model\ShipToAddress
      */
    protected $billing_address;
    
    /**
      * $items 
      * @var \gooten.api.model\PostOrderItem[]
      */
    protected $items;
    
    /**
      * $payment 
      * @var \gooten.api.model\OrderPayment
      */
    protected $payment;
    
    /**
      * $source_id Clients can submit an ID they use for the order here.
      * @var string
      */
    protected $source_id;
    
    /**
      * $is_pre_submit Submit the order into PrePayment status.
      * @var bool
      */
    protected $is_pre_submit;
    
    /**
      * $coupon_code 
      * @var string
      */
    protected $coupon_code;
    
    /**
      * $meta An optional Map<string,string> of misc properties.
      * @var \gooten.api.model\Meta
      */
    protected $meta;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->ship_to_address = $data["ship_to_address"];
            $this->billing_address = $data["billing_address"];
            $this->items = $data["items"];
            $this->payment = $data["payment"];
            $this->source_id = $data["source_id"];
            $this->is_pre_submit = $data["is_pre_submit"];
            $this->coupon_code = $data["coupon_code"];
            $this->meta = $data["meta"];
        }
    }
    
    /**
     * Gets ship_to_address
     * @return \gooten.api.model\ShipToAddress
     */
    public function getShipToAddress()
    {
        return $this->ship_to_address;
    }
  
    /**
     * Sets ship_to_address
     * @param \gooten.api.model\ShipToAddress $ship_to_address 
     * @return $this
     */
    public function setShipToAddress($ship_to_address)
    {
        
        $this->ship_to_address = $ship_to_address;
        return $this;
    }
    
    /**
     * Gets billing_address
     * @return \gooten.api.model\ShipToAddress
     */
    public function getBillingAddress()
    {
        return $this->billing_address;
    }
  
    /**
     * Sets billing_address
     * @param \gooten.api.model\ShipToAddress $billing_address 
     * @return $this
     */
    public function setBillingAddress($billing_address)
    {
        
        $this->billing_address = $billing_address;
        return $this;
    }
    
    /**
     * Gets items
     * @return \gooten.api.model\PostOrderItem[]
     */
    public function getItems()
    {
        return $this->items;
    }
  
    /**
     * Sets items
     * @param \gooten.api.model\PostOrderItem[] $items 
     * @return $this
     */
    public function setItems($items)
    {
        
        $this->items = $items;
        return $this;
    }
    
    /**
     * Gets payment
     * @return \gooten.api.model\OrderPayment
     */
    public function getPayment()
    {
        return $this->payment;
    }
  
    /**
     * Sets payment
     * @param \gooten.api.model\OrderPayment $payment 
     * @return $this
     */
    public function setPayment($payment)
    {
        
        $this->payment = $payment;
        return $this;
    }
    
    /**
     * Gets source_id
     * @return string
     */
    public function getSourceId()
    {
        return $this->source_id;
    }
  
    /**
     * Sets source_id
     * @param string $source_id Clients can submit an ID they use for the order here.
     * @return $this
     */
    public function setSourceId($source_id)
    {
        
        $this->source_id = $source_id;
        return $this;
    }
    
    /**
     * Gets is_pre_submit
     * @return bool
     */
    public function getIsPreSubmit()
    {
        return $this->is_pre_submit;
    }
  
    /**
     * Sets is_pre_submit
     * @param bool $is_pre_submit Submit the order into PrePayment status.
     * @return $this
     */
    public function setIsPreSubmit($is_pre_submit)
    {
        
        $this->is_pre_submit = $is_pre_submit;
        return $this;
    }
    
    /**
     * Gets coupon_code
     * @return string
     */
    public function getCouponCode()
    {
        return $this->coupon_code;
    }
  
    /**
     * Sets coupon_code
     * @param string $coupon_code 
     * @return $this
     */
    public function setCouponCode($coupon_code)
    {
        
        $this->coupon_code = $coupon_code;
        return $this;
    }
    
    /**
     * Gets meta
     * @return \gooten.api.model\Meta
     */
    public function getMeta()
    {
        return $this->meta;
    }
  
    /**
     * Sets meta
     * @param \gooten.api.model\Meta $meta An optional Map<string,string> of misc properties.
     * @return $this
     */
    public function setMeta($meta)
    {
        
        $this->meta = $meta;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\gooten.api.client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\gooten.api.client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
