<?php


/**
 * ProductOptionValueSettings
 *
 * PHP version 5
 *
 * @category Class
 * @package  gooten.api.client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace gooten.api.model;

use \ArrayAccess;
/**
 * ProductOptionValueSettings Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     gooten.api.client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductOptionValueSettings implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'icon_url' => 'string',
        'icon_type' => 'string',
        'color_rgba' => 'string'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'icon_url' => 'IconUrl',
        'icon_type' => 'IconType',
        'color_rgba' => 'ColorRgba'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'icon_url' => 'setIconUrl',
        'icon_type' => 'setIconType',
        'color_rgba' => 'setColorRgba'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'icon_url' => 'getIconUrl',
        'icon_type' => 'getIconType',
        'color_rgba' => 'getColorRgba'
    );
  
    
    /**
      * $icon_url 
      * @var string
      */
    protected $icon_url;
    
    /**
      * $icon_type 
      * @var string
      */
    protected $icon_type;
    
    /**
      * $color_rgba 
      * @var string
      */
    protected $color_rgba;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->icon_url = $data["icon_url"];
            $this->icon_type = $data["icon_type"];
            $this->color_rgba = $data["color_rgba"];
        }
    }
    
    /**
     * Gets icon_url
     * @return string
     */
    public function getIconUrl()
    {
        return $this->icon_url;
    }
  
    /**
     * Sets icon_url
     * @param string $icon_url 
     * @return $this
     */
    public function setIconUrl($icon_url)
    {
        
        $this->icon_url = $icon_url;
        return $this;
    }
    
    /**
     * Gets icon_type
     * @return string
     */
    public function getIconType()
    {
        return $this->icon_type;
    }
  
    /**
     * Sets icon_type
     * @param string $icon_type 
     * @return $this
     */
    public function setIconType($icon_type)
    {
        
        $this->icon_type = $icon_type;
        return $this;
    }
    
    /**
     * Gets color_rgba
     * @return string
     */
    public function getColorRgba()
    {
        return $this->color_rgba;
    }
  
    /**
     * Sets color_rgba
     * @param string $color_rgba 
     * @return $this
     */
    public function setColorRgba($color_rgba)
    {
        
        $this->color_rgba = $color_rgba;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\gooten.api.client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\gooten.api.client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}


